Create an app
markoff96/react_todo pull request #2
Opened 2023-02-19 09:42 UTC by markoff96

I made an input field and todos section, still need to add complete and delete functions

2023-02-19 11:25 UTC, RomanAchilov requested changes
В целом молодец

2023-02-19 11:25 UTC, RomanAchilov commented on src/App.css
> +body{
Настрой eslint, prettier

2023-02-19 11:25 UTC, RomanAchilov commented on src/App.js
> +  const addToHandler = (text) => {
```suggestion
  const addTodo = (text) => {
```
Так получше

2023-02-19 11:25 UTC, RomanAchilov commented on src/App.js
> +    <Input addTodo={addToHandler} />
```suggestion
    <Input addTodo={addTodo} />
```

2023-02-19 11:25 UTC, RomanAchilov commented on src/components/Input.js
> +export default Input
Почитай про лайн ендингс

2023-02-19 11:25 UTC, RomanAchilov commented on src/components/ToDoList.js
> +       todos.map((todo, index) => <Todo key={index} todo={todo}/>)
В случае с туду листом для элементов массива ключ как индекс юзать, плохая затея. Почитай в доке реакта за keys

2023-02-20 18:39 UTC, markoff96 reviewed
Обновления от сенсея

2023-02-20 19:01 UTC, RomanAchilov requested changes
Ну притиер и еслинт до сих пор не настроены, а прошлые замечания об этом закрыты - грустно

2023-02-20 19:01 UTC, RomanAchilov commented on src/components/Input.js
> +    if (!text){
Ну такое себе.
Если и возвращать что-то, то к примеру тригерить рендер ошибки или нотификации с текстом

2023-02-20 19:01 UTC, RomanAchilov commented on src/components/Input.js
> +    if (!text){
Иначе легче оставить if (text) addTodo

2023-02-20 19:01 UTC, RomanAchilov commented on src/components/ToDoList.js
> +            <Todo key={index} todo={todo} deleteTodo={deleteTodo} index={index}/>)}
Key так и остался по индексу. Читал за индексы в списках?

2023-03-02 14:53 UTC, closed without merging